# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

name: $(BuildID)
  
trigger:
  batch: true
  branches:
    include:
    - master
    - korg

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: maven
  - name: BUILD_NUMBER 
    value: '$(Build.BuildNumber)'
  - name: BUILD_NAME 
    value: '$(Build.DefinitionName)'


steps:
- checkout: self
  persistCredentials: true
  clean: true
- script: mkdir ~/.ssh
- script: ssh-keyscan -p $(deployPort) -H $(deployServer) >> ~/.ssh/known_hosts
- task: Gradle@2
  inputs:
    workingDirectory: 'openpos-assemble'
    options: '--stacktrace -PbuildNumber=$(Build.BuildNumber) -PbuildName=$(Build.DefinitionName) -PgitHash=$(Build.SourceVersion) -PgitBranch=$(Build.SourceBranchName) -PdeployUser=$(deployUser) -PdeployPassword=$(deployPassword) -PdeployUploadUrl=$(deployUploadUrl)'
    gradleWrapperFile: 'openpos-assemble/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST*.xml'
    tasks: 'jacocoRootReport deploy generateSourceArtifact'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Server Code Coverage'
  inputs: 
    codeCoverageTool: JaCoCo
    summaryFileLocation: 'openpos-assemble/**/jacocoTestReport.xml'
- task: PublishCodeCoverageResults@1
  displayName: 'Publish Client Code Coverage'
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '**/*coverage.xml'
- task: PublishBuildArtifacts@1
  displayName: 'Publish server source for downstream pipeline consumption'
  inputs:
    pathtoPublish: 'openpos-assemble/build/openpos-server-core-lib'
    artifactName: 'openpos-server-core-lib'
